pipeline:

  test-project:
    image: golang:1.12.7
    commands:
      - go get -v github.com/UKHomeOffice/dapperdox
      - cd $GOPATH/src/github.com/UKHomeOffice/dapperdox
      - git checkout ${DRONE_COMMIT_BRANCH}
      - go get
      - go test ./spec
    when:
      event: [push, pull_request, tag]

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - docker_password
    environment:
      - DOCKER_USERNAME=ukhomeofficedigital+dapperdox
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dapperdox
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push
